pipeline {
    agent none
    stages {
        stage('Build Jar') {
            agent {
                docker {
                    image 'maven:3.9.9-ibm-semeru-11-focal'
                    args '-u root -v /tmp/m2:/root/.m2'
                }
            }
            steps {
                bat 'mvn clean package -DskipTests'
            }
        }
        stage('Build Image') {
            steps {
                script {
                    app = docker.build('diwakar15/selenium')
                }
            }
        }

        stage('Push Image'){
            steps{
                script {
                    // registry url is blank for dockerhub
                    docker.withRegistry('', 'dockerhub-creds') {
                        app.push("latest")
                    }
                }
            }
        }

    }
}